-----------------------------------
-- zones
-----------------------------------
return {
    abyssea_attohwa = require("scripts/globals/fishing/zones/abyssea_attohwa"),
    abyssea_misareaux = require("scripts/globals/fishing/zones/abyssea_misareaux"),
    abyssea_tahrongi = require("scripts/globals/fishing/zones/abyssea_tahrongi"),
    al_zahbi = require("scripts/globals/fishing/zones/al_zahbi"),
    bastok_markets = require("scripts/globals/fishing/zones/bastok_markets"),
    bastok_mines = require("scripts/globals/fishing/zones/bastok_mines"),
    beadeaux = require("scripts/globals/fishing/zones/beadeaux"),
    bibiki_bay = require("scripts/globals/fishing/zones/bibiki_bay"),
    bostaunieux_obl = require("scripts/globals/fishing/zones/bostaunieux_obl"),
    buburimu_peninsula = require("scripts/globals/fishing/zones/buburimu_peninsula"),
    carpenters_landing = require("scripts/globals/fishing/zones/carpenters_landing"),
    ceizak_battlegrounds = require("scripts/globals/fishing/zones/ceizak_battlegrounds"),
    cervantes_gully = require("scripts/globals/fishing/zones/cervantes_gully"),
    crawlers_nest = require("scripts/globals/fishing/zones/crawlers_nest"),
    dhoro_i_kamuy = require("scripts/globals/fishing/zones/dhoro_i_kamuy"),
    east_ronfaure = require("scripts/globals/fishing/zones/east_ronfaure"),
    east_sarutabaruta = require("scripts/globals/fishing/zones/east_sarutabaruta"),
    eldieme_necropolis = require("scripts/globals/fishing/zones/eldieme_necropolis"),
    empyreal_paradox = require("scripts/globals/fishing/zones/empyreal_paradox"),
    escha_ruaun = require("scripts/globals/fishing/zones/escha_ruaun"),
    escha_zitah = require("scripts/globals/fishing/zones/escha_zitah"),
    giddeus = require("scripts/globals/fishing/zones/giddeus"),
    jugner_forest = require("scripts/globals/fishing/zones/jugner_forest"),
    korroloka_tunnel = require("scripts/globals/fishing/zones/korroloka_tunnel"),
    labyrinth_of_onzozo = require("scripts/globals/fishing/zones/labyrinth_of_onzozo"),
    la_theine_plateau = require("scripts/globals/fishing/zones/la_theine_plateau"),
    lighthouse_of_olton = require("scripts/globals/fishing/zones/lighthouse_of_olton"),
    lower_jeuno = require("scripts/globals/fishing/zones/lower_jeuno"),
    meriphataud_mountains = require("scripts/globals/fishing/zones/meriphataud_mountains"),
    mhuara = require("scripts/globals/fishing/zones/mhuara"),
    mount_zhayolm = require("scripts/globals/fishing/zones/mount_zhayolm"),
    norg = require("scripts/globals/fishing/zones/norg"),
    north_gustaberg = require("scripts/globals/fishing/zones/north_gustaberg"),
    northern_san_doria = require("scripts/globals/fishing/zones/northern_san_doria"),
    port_bastok = require("scripts/globals/fishing/zones/port_bastok"),
    port_jeuno = require("scripts/globals/fishing/zones/port_jeuno"),
    port_san_doria = require("scripts/globals/fishing/zones/port_san_doria"),
    port_windurst = require("scripts/globals/fishing/zones/port_windurst"),
    qufim_island = require("scripts/globals/fishing/zones/qufim_island"),
    reisenjima = require("scripts/globals/fishing/zones/reisenjima"),
    ronfaure = require("scripts/globals/fishing/zones/ronfaure"),
    sauromugue_champagne = require("scripts/globals/fishing/zones/sauromugue_champagne"),
    selbina = require("scripts/globals/fishing/zones/selbina"),
    silver_mirror = require("scripts/globals/fishing/zones/silver_mirror"),
    south_gustaberg = require("scripts/globals/fishing/zones/south_gustaberg"),
    southern_san_doria = require("scripts/globals/fishing/zones/southern_san_doria"),
    the_sanctuary_of_zi_tah = require("scripts/globals/fishing/zones/the_sanctuary_of_zi_tah"),
    valkurm_dunes = require("scripts/globals/fishing/zones/valkurm_dunes"),
    windurst_walls = require("scripts/globals/fishing/zones/windurst_walls"),
    windurst_waters = require("scripts/globals/fishing/zones/windurst_waters"),
    west_ronfaure = require("scripts/globals/fishing/zones/west_ronfaure"),
    west_sarutabaruta = require("scripts/globals/fishing/zones/west_sarutabaruta"),
}

