-----------------------------------
-- zones
-----------------------------------

return {
    batallia_downs       = require("scripts/globals/fishing/zones/batallia_downs"),
    bastok_markets       = require("scripts/globals/fishing/zones/bastok_markets"),
    bastok_mines         = require("scripts/globals/fishing/zones/bastok_mines"),
    beaucedine_glacier   = require("scripts/globals/fishing/zones/beaucedine_glacier"),
    buburimu_peninsula   = require("scripts/globals/fishing/zones/buburimu_peninsula"),
    dangruf_wadi         = require("scripts/globals/fishing/zones/dangruf_wadi"),
    davoi                = require("scripts/globals/fishing/zones/davoi"),
    east_ronfaure        = require("scripts/globals/fishing/zones/east_ronfaure"),
    east_sarutabaruta    = require("scripts/globals/fishing/zones/east_sarutabaruta"),
    ferry_mhaura_selbina = require("scripts/globals/fishing/zones/ferry_mhaura_selbina"),
    ghelsba_outpost      = require("scripts/globals/fishing/zones/ghelsba_outpost"),
    giddeus              = require("scripts/globals/fishing/zones/giddeus"),
    gusgen_mines         = require("scripts/globals/fishing/zones/gusgen_mines"),
    jugner_forest        = require("scripts/globals/fishing/zones/jugner_forest"),
    la_theine_plateau    = require("scripts/globals/fishing/zones/la_theine_plateau"),
    lower_jeuno          = require("scripts/globals/fishing/zones/lower_jeuno"),
    mhuara               = require("scripts/globals/fishing/zones/mhuara"),
    north_gustaberg      = require("scripts/globals/fishing/zones/north_gustaberg"),
    northern_san_doria   = require("scripts/globals/fishing/zones/northern_san_doria"),
    ordelles_caves       = require("scripts/globals/fishing/zones/ordelles_caves"),
    pashhow_marshlands   = require("scripts/globals/fishing/zones/pashhow_marshlands"),
    palborough_mines     = require("scripts/globals/fishing/zones/palborough_mines"),
    port_bastok          = require("scripts/globals/fishing/zones/port_bastok"),
    port_jeuno           = require("scripts/globals/fishing/zones/port_jeuno"),
    port_san_doria       = require("scripts/globals/fishing/zones/port_san_doria"),
    port_windurst        = require("scripts/globals/fishing/zones/port_windurst"),
    qufim_island         = require("scripts/globals/fishing/zones/qufim_island"),
    rolanberry_fields    = require("scripts/globals/fishing/zones/rolanberry_fields"),
    sauromugue_champaign = require("scripts/globals/fishing/zones/sauromugue_champaign"),
    selbina              = require("scripts/globals/fishing/zones/selbina"),
    south_gustaberg      = require("scripts/globals/fishing/zones/south_gustaberg"),
    valkurm_dunes        = require("scripts/globals/fishing/zones/valkurm_dunes"),
    west_ronfaure        = require("scripts/globals/fishing/zones/west_ronfaure"),
    west_sarutabaruta    = require("scripts/globals/fishing/zones/west_sarutabaruta"),
    windurst_walls       = require("scripts/globals/fishing/zones/windurst_walls"),
    windurst_waters      = require("scripts/globals/fishing/zones/windurst_waters"),
    windurst_woods       = require("scripts/globals/fishing/zones/windurst_woods"),
    zeruhn_mines         = require("scripts/globals/fishing/zones/zeruhn_mines"),
}

