name: 'Label and close stale PRs'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 1 * * *'

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: -1
          days-before-pr-stale: 14
          days-before-pr-close: 60
          stale-pr-message: |
            This PR has been automatically marked as stale because
            it has not had recent activity. It will be closed if no
            further activity occurs.
          stale-pr-label: 'stale'
          close-pr-label: 'abandoned'
          exempt-pr-labels: 'hold'
          remove-pr-stale-when-updated: true
